# Code generated by graphql-codegen from `app.graphql`. DO NOT EDIT.

import builtins as _builtins
import typing as _typing
from bookshop.client.runtime import _compat
from bookshop.client.runtime import _reflection
from bookshop.client import runtime as _runtime
from bookshop.client.schema import enum as _enum
from bookshop.client.schema import input as _input
from bookshop.client import _scalar

class _BookCard_author(_compat.TypedDict, closed=True):
    name: _builtins.str

class BookCard(_compat.TypedDict):
    """What a book shows in a list."""
    id: _builtins.str
    title: _builtins.str
    price: _scalar.Money
    author: _BookCard_author | None
    """Null for an anthology, which has no single author."""

class GetBookVariables(_compat.TypedDict, closed=True):
    lookup: _typing.Required[_input.BookLookup]
    """An identifier or an ISBN."""
    withReviews: _typing.NotRequired[_builtins.bool]

class _GetBookData_book_reviews(_compat.TypedDict, closed=True):
    rating: _builtins.int
    """From 1 to 5."""
    text: _builtins.str | None
    postedAt: _scalar.DateTime

class _GetBookData_book(BookCard, closed=True):
    isbn: _scalar.ISBN
    pageCount: _builtins.int
    reviews: _typing.NotRequired[_builtins.list[_GetBookData_book_reviews]]

class GetBookData(_compat.TypedDict, closed=True):
    book: _typing.Annotated[_GetBookData_book, _reflection.NON_NULL]
    """The book with this identifier or ISBN."""

GetBook: _runtime.Operation[_typing.Literal['query'], GetBookVariables, GetBookData] = _runtime.Operation(operation_type='query', name='GetBook', document="""query GetBook($lookup§: BookLookup!, $withReviews§: Boolean! = false) {
  book§: book(lookup: $lookup§) {
    ...BookCard
    isbn
    pageCount
    reviews @include(if: $withReviews§) {
      rating
      text
      postedAt
    }
  }
}

fragment BookCard on Book {
  id
  title
  price
  author {
    name
  }
}""", variables_type=GetBookVariables, data_type=GetBookData)
"""A book, with its reviews when asked for."""

class SearchVariables(_compat.TypedDict, closed=True):
    text: _typing.Required[_builtins.str]

_SearchData_search_Book_Base = _compat.TypedDict('_SearchData_search_Book_Base', {'__typename': _compat.ReadOnly[_typing.Literal['Book']]})

class _SearchData_search_Book(_SearchData_search_Book_Base, closed=True):
    title: _builtins.str
    price: _scalar.Money

_SearchData_search_Magazine_Base = _compat.TypedDict('_SearchData_search_Magazine_Base', {'__typename': _compat.ReadOnly[_typing.Literal['Magazine']]})

class _SearchData_search_Magazine(_SearchData_search_Magazine_Base, closed=True):
    title: _builtins.str
    price: _scalar.Money

_SearchData_search_Audiobook_Base = _compat.TypedDict('_SearchData_search_Audiobook_Base', {'__typename': _compat.ReadOnly[_typing.Literal['Audiobook']]})

class _SearchData_search_Audiobook(_SearchData_search_Audiobook_Base, closed=True):
    title: _builtins.str
    price: _scalar.Money

_SearchData_search_Author_Base = _compat.TypedDict('_SearchData_search_Author_Base', {'__typename': _compat.ReadOnly[_typing.Literal['Author']]})

class _SearchData_search_Author(_SearchData_search_Author_Base, closed=True):
    name: _builtins.str

type _SearchData_search = _SearchData_search_Book | _SearchData_search_Magazine | _SearchData_search_Audiobook | _SearchData_search_Author

class SearchData(_compat.TypedDict, closed=True):
    search: _builtins.list[_SearchData_search]
    """Everything whose title or name contains the text."""

Search: _runtime.Operation[_typing.Literal['query'], SearchVariables, SearchData] = _runtime.Operation(operation_type='query', name='Search', document="""query Search($text§: String!) {
  search§: search(text: $text§) {
    __typename
    ... on Publication {
      title
      price
    }
    ... on Author {
      name
    }
  }
}""", variables_type=SearchVariables, data_type=SearchData)

class ListBooksVariables(_compat.TypedDict, closed=True):
    filter: _typing.NotRequired[_input.BookFilter | None]
    first: _typing.NotRequired[_builtins.int | None]

class _ListBooksData_books(BookCard, closed=True):
    genre: _enum.Genre

class ListBooksData(_compat.TypedDict, closed=True):
    books: _builtins.list[_ListBooksData_books]
    """The books matching the filter, at most `first` of them."""

ListBooks: _runtime.Operation[_typing.Literal['query'], ListBooksVariables, ListBooksData] = _runtime.Operation(operation_type='query', name='ListBooks', document="""query ListBooks($filter§: BookFilter, $first§: Int) {
  books§: books(filter: $filter§, first: $first§) {
    ...BookCard
    genre
  }
}

fragment BookCard on Book {
  id
  title
  price
  author {
    name
  }
}""", variables_type=ListBooksVariables, data_type=ListBooksData)

class GetPublicationVariables(_compat.TypedDict, closed=True):
    id: _typing.Required[_builtins.str]

_GetPublicationData_publication_Book_Base = _compat.TypedDict('_GetPublicationData_publication_Book_Base', {'__typename': _compat.ReadOnly[_typing.Literal['Book']]})

class _GetPublicationData_publication_Book(_GetPublicationData_publication_Book_Base, closed=True):
    title: _builtins.str
    pages: _builtins.int
    isbn: _scalar.ISBN

_GetPublicationData_publication_Magazine_Base = _compat.TypedDict('_GetPublicationData_publication_Magazine_Base', {'__typename': _compat.ReadOnly[_typing.Literal['Magazine']]})

class _GetPublicationData_publication_Magazine(_GetPublicationData_publication_Magazine_Base, closed=True):
    title: _builtins.str
    pages: _builtins.int

_GetPublicationData_publication_Audiobook_Base = _compat.TypedDict('_GetPublicationData_publication_Audiobook_Base', {'__typename': _compat.ReadOnly[_typing.Literal['Audiobook']]})

class _GetPublicationData_publication_Audiobook(_GetPublicationData_publication_Audiobook_Base, closed=True):
    title: _builtins.str
    duration: _builtins.int
    """Its length, in minutes."""

type _GetPublicationData_publication = _GetPublicationData_publication_Book | _GetPublicationData_publication_Magazine | _GetPublicationData_publication_Audiobook
"""Something the bookshop sells."""

class GetPublicationData(_compat.TypedDict, closed=True):
    publication: _GetPublicationData_publication | None
    """The publication with this identifier."""

GetPublication: _runtime.Operation[_typing.Literal['query'], GetPublicationVariables, GetPublicationData] = _runtime.Operation(operation_type='query', name='GetPublication', document="""query GetPublication($id§: ID!) {
  publication§: publication(id: $id§) {
    __typename
    title
    ... on Printed {
      pages: pageCount
      ... on Book {
        isbn
      }
    }
    ... on Audiobook {
      duration
    }
  }
}""", variables_type=GetPublicationVariables, data_type=GetPublicationData)

class GetSavedSearchVariables(_compat.TypedDict, closed=True):
    name: _typing.Required[_builtins.str]

class _GetSavedSearchData_savedSearch(_compat.TypedDict, closed=True):
    value: _input.BookFilter | None

class GetSavedSearchData(_compat.TypedDict, closed=True):
    savedSearch: _GetSavedSearchData_savedSearch | None
    """The filter of the saved search with this name, exactly as it was saved."""

GetSavedSearch: _runtime.Operation[_typing.Literal['query'], GetSavedSearchVariables, GetSavedSearchData] = _runtime.Operation(operation_type='query', name='GetSavedSearch', document="""query GetSavedSearch($name§: String!) {
  savedSearch§: savedSearch(name: $name§) {
    value
  }
}""", variables_type=GetSavedSearchVariables, data_type=GetSavedSearchData)

class PlaceOrderVariables(_compat.TypedDict, closed=True):
    input: _typing.Required[_input.PlaceOrderInput]

class _PlaceOrderData_placeOrder(_compat.TypedDict, closed=True):
    id: _builtins.str
    status: _enum.OrderStatus
    total: _scalar.Money
    placedAt: _scalar.DateTime

class PlaceOrderData(_compat.TypedDict, closed=True):
    placeOrder: _PlaceOrderData_placeOrder
    """Place an order for the given lines."""

PlaceOrder: _runtime.Operation[_typing.Literal['mutation'], PlaceOrderVariables, PlaceOrderData] = _runtime.Operation(operation_type='mutation', name='PlaceOrder', document="""mutation PlaceOrder($input§: PlaceOrderInput!) {
  placeOrder§: placeOrder(input: $input§) {
    id
    status
    total
    placedAt
  }
}""", variables_type=PlaceOrderVariables, injections={'idempotencyKey': _builtins.frozenset({('input',)})}, data_type=PlaceOrderData)

class CancelOrderVariables(_compat.TypedDict, closed=True):
    input: _typing.Required[_input.CancelOrderInput]

class _CancelOrderData_cancelOrder(_compat.TypedDict, closed=True):
    id: _builtins.str
    status: _enum.OrderStatus

class CancelOrderData(_compat.TypedDict, closed=True):
    cancelOrder: _CancelOrderData_cancelOrder | None
    """Cancel an order that has not shipped yet.

    Null, with an error saying why, for an order that has.
    Nullable so that when several orders are canceled in one request, one failure leaves the others' results intact."""

CancelOrder: _runtime.Operation[_typing.Literal['mutation'], CancelOrderVariables, CancelOrderData] = _runtime.Operation(operation_type='mutation', name='CancelOrder', document="""mutation CancelOrder($input§: CancelOrderInput!) {
  cancelOrder§: cancelOrder(input: $input§) {
    id
    status
  }
}""", variables_type=CancelOrderVariables, injections={'idempotencyKey': _builtins.frozenset({('input',)})}, data_type=CancelOrderData)

class OnOrderStatusChangedVariables(_compat.TypedDict, closed=True):
    orderId: _typing.Required[_builtins.str]

class _OnOrderStatusChangedData_orderStatusChanged(_compat.TypedDict, closed=True):
    id: _builtins.str
    status: _enum.OrderStatus

class OnOrderStatusChangedData(_compat.TypedDict, closed=True):
    orderStatusChanged: _OnOrderStatusChangedData_orderStatusChanged
    """The order, each time its status changes."""

OnOrderStatusChanged: _runtime.Operation[_typing.Literal['subscription'], OnOrderStatusChangedVariables, OnOrderStatusChangedData] = _runtime.Operation(operation_type='subscription', name='OnOrderStatusChanged', document="""subscription OnOrderStatusChanged($orderId: ID!) {
  orderStatusChanged(orderId: $orderId) {
    id
    status
  }
}""", variables_type=OnOrderStatusChangedVariables, data_type=OnOrderStatusChangedData)
