# Code generated by graphql-codegen from `get_order.graphql`. DO NOT EDIT.

import builtins as _builtins
import typing as _typing
from bookshop.client.runtime import _compat
from bookshop.client import runtime as _runtime
from bookshop.client.schema import enum as _enum

class GetOrderVariables(_compat.TypedDict, closed=True):
    id: _typing.Required[_builtins.str]

class _GetOrderData_order(_compat.TypedDict, closed=True):
    id: _builtins.str
    status: _enum.OrderStatus

class GetOrderData(_compat.TypedDict, closed=True):
    order: _GetOrderData_order | None
    """The order with this identifier."""

GetOrder: _runtime.Operation[_typing.Literal['query'], GetOrderVariables, GetOrderData] = _runtime.Operation(operation_type='query', name='GetOrder', document="""query GetOrder($id§: ID!) {
  order§: order(id: $id§) {
    id
    status
  }
}""", variables_type=GetOrderVariables, data_type=GetOrderData)
