# Code generated by graphql-codegen from `_introspection.graphql`. DO NOT EDIT.

import builtins as _builtins
import typing as _typing
from graphql_codegen.runtime import _compat
from graphql_codegen.runtime import _reflection
from graphql_codegen import runtime as _runtime

class _FieldNames_fields(_compat.TypedDict, closed=True):
    """Object and Interface types are described by a list of Fields, each of which has a name, potentially a list of arguments, and a return type."""
    name: _builtins.str

class FieldNames(_compat.TypedDict):
    """The fundamental unit of any GraphQL Schema is the type. There are many kinds of types in GraphQL as represented by the `__TypeKind` enum.

    Depending on the kind of a type, certain fields describe information about that type. Scalar types provide no information beyond a name, description and optional `specifiedByURL`, while Enum types provide their values. Object and Interface types provide the fields they describe. Abstract types, Union and Interface, provide the Object types possible at runtime. List and NonNull types compose other types."""
    fields: _typing.Annotated[_builtins.list[_FieldNames_fields], _reflection.NON_NULL]

class IntrospectionProbeVariables(_compat.TypedDict, closed=True):
    ...

class IntrospectionProbeData(_compat.TypedDict, closed=True):
    schema: _typing.Annotated[FieldNames, _reflection.NON_NULL]
    """Request the type information of a single type."""
    type: _typing.Annotated[FieldNames, _reflection.NON_NULL]
    """Request the type information of a single type."""
    inputValue: _typing.Annotated[FieldNames, _reflection.NON_NULL]
    """Request the type information of a single type."""
    directive: _typing.Annotated[FieldNames, _reflection.NON_NULL]
    """Request the type information of a single type."""

IntrospectionProbe: _runtime.Operation[_typing.Literal['query'], IntrospectionProbeVariables, IntrospectionProbeData] = _runtime.Operation(operation_type='query', name='IntrospectionProbe', document="""query IntrospectionProbe {
  schema§: __type(name: "__Schema") {
    ...FieldNames
  }
  type§: __type(name: "__Type") {
    ...FieldNames
  }
  inputValue§: __type(name: "__InputValue") {
    ...FieldNames
  }
  directive§: __type(name: "__Directive") {
    ...FieldNames
  }
}

fragment FieldNames on __Type {
  fields {
    name
  }
}""", variables_type=IntrospectionProbeVariables, data_type=IntrospectionProbeData)
"""Which fields the server's introspection types have.
The full introspection query then asks only for those, since an older server rejects a field it does not know."""
