# Code generated by graphql-codegen. DO NOT EDIT.

import builtins as _builtins
import typing as _typing
from .runtime import _reflection
from datetime import datetime as _datetime
from ..scalar import decode_datetime as _decode_datetime
from ..scalar import encode_datetime as _encode_datetime
from ..scalar import ISBN as _ISBN
from decimal import Decimal as _Decimal
from uuid import UUID as _UUID

type DateTime = _typing.Annotated[_datetime, _reflection.Codec(decode=_decode_datetime, encode=_encode_datetime)]

type ISBN = _ISBN

type Money = _typing.Annotated[_Decimal, _reflection.Codec(decode=_Decimal, encode=_builtins.str)]

type UUID = _typing.Annotated[_UUID, _reflection.Codec(decode=_UUID, encode=_builtins.str)]
