# Code generated by graphql-codegen. DO NOT EDIT.

import collections.abc as _abc
import typing as _typing
from .runtime import _compat
from .runtime import injection as _injection
from .runtime import OMITTED as _OMITTED
from . import _scalar

class InjectorFunctions(_compat.TypedDict, closed=True):
    """The functions supplying each injected value, by name.

    Where the value may be null, one returning `OMITTED` leaves it out, and one returning `None` sends `null`."""
    idempotencyKey: _typing.NotRequired[_abc.Callable[[], _scalar.UUID | None | _OMITTED]]

def injectors(functions: InjectorFunctions, /) -> _injection._Injectors:
    """Return what a client calls to supply the injected values, each serialized as its type says."""
    return _injection._Injectors(functions, injector_functions_type=InjectorFunctions)
