# Code generated by graphql-codegen. DO NOT EDIT.

from collections.abc import Callable, Mapping, Sequence
from json import JSONDecodeError, loads
from typing import Any, Final, assert_never, cast, final

from ._literal import OperationType
from ._merge import encode_body, split_merged_data, split_merged_errors
from ._reflection import Convert
from .error import (
    ClientError,
    Error,
    ExecutionError,
    ProtocolError,
    RequestError,
    UnexpectedNullError,
)
from .injection import _Injectors
from .operation import Operation, Request


@final
class PreparedRequest[Data]:
    """A call without its IO and awaiting, which are the clients' part."""

    __slots__ = ("_body", "parse")

    def __init__(self, body: bytes, /, *, parse: Callable[[bytes], Data]) -> None:
        self._body: Final = body
        self.parse: Final = parse

    def __bytes__(self) -> bytes:
        return self._body


def resolve_variables(
    operation: Operation[OperationType, Any, object],
    variables: Mapping[str, object],
    /,
    *,
    injectors: _Injectors | None = None,
) -> Mapping[str, object]:
    """The caller's are never mutated: serializing copies them, and injecting copies what it writes into."""
    serialize = operation._variables_serializer
    values = (
        variables
        if serialize is None
        else cast(Mapping[str, object], serialize(variables))
    )
    return (
        values
        if injectors is None
        else injectors._inject(values, injections=operation._injections)
    )


def prepare[Data](
    request: Request[OperationType, Data], /, *, injectors: _Injectors | None = None
) -> PreparedRequest[Data]:
    operation = request._operation
    variables = resolve_variables(operation, request._variables, injectors=injectors)

    def parse(raw: bytes, /) -> Data:
        try:
            return parse_data(operation, raw)
        except ClientError as error:
            error.add_note(_origin_note(operation._name, variables))

            if isinstance(error, ExecutionError):
                match request._on_execution_error:
                    case "raise":
                        pass
                    case "return":
                        # `Data` is the request's data type or its error: see `Request.returning_error()`.
                        return cast(Data, error)
                    case _ as never:
                        assert_never(never)

            raise

    return PreparedRequest(operation._request_body(variables), parse=parse)


def parse_data[Data](
    operation: Operation[OperationType, Any, Data], raw: bytes, /
) -> Data:
    """Nothing is validated: the data is trusted to match its static type, from this cast on."""
    data = parse_response(raw, partial_data_parser=operation._partial_data_parser)

    if operation._data_parser is not None:
        operation._data_parser(data)

    return cast(Data, data)


def _execution_error[Data](
    operation: Operation[OperationType, Any, Data],
    errors: Sequence[Error],
    /,
    *,
    data: Mapping[str, object] | None,
    extensions: Mapping[str, object] | None,
) -> ExecutionError[Data]:
    return ExecutionError[Data](
        errors,
        data=data,
        extensions=extensions,
        partial_data_parser=operation._partial_data_parser,
    )


def parse_response(
    raw: bytes, /, *, partial_data_parser: Convert | None
) -> Mapping[str, object]:
    """A response with errors but no `data` entry is the spec's request error result."""
    try:
        payload = loads(raw)
    except JSONDecodeError as error:
        raise ProtocolError(
            f"Expected a JSON response but got: {raw[:200]!r}."
        ) from error

    if not isinstance(payload, dict):
        raise ProtocolError(f"Expected a JSON object response but got: {raw[:200]!r}.")

    errors = payload.get("errors")

    if errors:
        # Trusted to be the spec's errors, as the data is trusted to match its type.
        formatted = cast(list[Error], errors)
        extensions = payload.get("extensions")

        if "data" not in payload:
            raise RequestError(formatted, extensions=extensions)

        raise ExecutionError(
            formatted,
            data=payload["data"],
            extensions=extensions,
            partial_data_parser=partial_data_parser,
        )

    data = payload.get("data")

    if not isinstance(data, dict):
        raise ProtocolError(
            f"Expected the response to carry `data` but got: {raw[:200]!r}."
        )

    # The keys of a JSON object are strings.
    return cast(Mapping[str, object], data)


def _origin_note(operation_name: str, variables: Mapping[str, object], /) -> str:
    """The variables are shown by :func:`repr`, so that a :class:`str` subclass redacting its own keeps a secret out of logs."""
    return f"Raised by `{operation_name}` with variables {variables!r}."


def _raises_execution_error(request: Request[OperationType, object], /) -> bool:
    match request._on_execution_error:
        case "raise":
            return True
        case "return":
            return False
        case _ as never:
            assert_never(never)


def _prepare_merged(
    requests: Sequence[Request[OperationType, object]],
    /,
    *,
    injectors: _Injectors | None,
) -> PreparedRequest[tuple[object, ...]]:
    operations = [request._operation for request in requests]
    # Resolved now rather than when the response comes back, like a lone request's.
    variables = [
        resolve_variables(request._operation, request._variables, injectors=injectors)
        for request in requests
    ]
    body = encode_body(list(zip(operations, variables, strict=True)))
    count = len(requests)

    def parse(raw: bytes, /) -> tuple[object, ...]:
        failures: dict[int, ExecutionError[object]] = {}

        try:
            data = parse_response(raw, partial_data_parser=None)
        except ExecutionError as error:
            # With no data, the merge failed as a whole, which is no one request's error to return.
            if error.data is None:
                raise

            split = split_merged_data(error.data, count=count)

            for index, (operation, operation_variables, operation_errors) in enumerate(
                zip(
                    operations,
                    variables,
                    split_merged_errors(error.errors, count=count),
                    strict=True,
                )
            ):
                if operation_errors:
                    failure = _execution_error(
                        operation,
                        operation_errors,
                        data=split[index],
                        extensions=error.extensions,
                    )
                    failure.add_note(_origin_note(operation._name, operation_variables))
                    failures[index] = failure

            # A call returns or raises: when one failing request raises its error, the group holds every failure, those of requests returning theirs included.
            if any(_raises_execution_error(requests[index]) for index in failures):
                raise ExceptionGroup(
                    f"{len(failures)} of the {count} merged operations raised.",
                    list(failures.values()),
                ) from None
        else:
            split = split_merged_data(data, count=count)

        for index, (operation, operation_variables, operation_data) in enumerate(
            zip(operations, variables, split, strict=True)
        ):
            if index not in failures and operation._data_parser is not None:
                try:
                    operation._data_parser(operation_data)
                except UnexpectedNullError as null_error:
                    null_error.add_note(
                        _origin_note(operation._name, operation_variables)
                    )
                    raise

        return tuple(
            failures.get(index, operation_data)
            for index, operation_data in enumerate(split)
        )

    return PreparedRequest(body, parse=parse)


def prepare_requests(
    requests: object, /, *, injectors: _Injectors | None
) -> PreparedRequest[Any] | None:
    if isinstance(requests, Request):
        return prepare(requests, injectors=injectors)

    assert isinstance(requests, Sequence)
    return _prepare_merged(requests, injectors=injectors) if requests else None
