# Code generated by graphql-codegen. DO NOT EDIT.

from collections.abc import AsyncGenerator, Callable, Generator, Sequence
from contextlib import aclosing, closing
from typing import Any, Final, Generic, Literal, final, overload

from ._compat import TypeVar
from ._prepare import prepare, prepare_requests
from ._transport import (
    AsyncSubscriptionTransport,
    AsyncTransport,
    SubscriptionTransport,
    Transport,
)
from .injection import _Injectors
from .operation import Request

# A client's transport, whose signature types the arguments each call accepts: none, unless it says otherwise.
# Covariant, so that a client over a transport is a client over any `Protocol` the transport satisfies.
# Legacy `TypeVar`s, since a default for a PEP 695 type parameter needs Python 3.13.
_Transport_co = TypeVar(
    "_Transport_co", bound=Transport[...], covariant=True, default=Transport[[]]
)
_AsyncTransport_co = TypeVar(
    "_AsyncTransport_co",
    bound=AsyncTransport[...],
    covariant=True,
    default=AsyncTransport[[]],
)
_SubscriptionTransport_co = TypeVar(
    "_SubscriptionTransport_co",
    bound=SubscriptionTransport[...],
    covariant=True,
    default=SubscriptionTransport[[]],
)
_AsyncSubscriptionTransport_co = TypeVar(
    "_AsyncSubscriptionTransport_co",
    bound=AsyncSubscriptionTransport[...],
    covariant=True,
    default=AsyncSubscriptionTransport[[]],
)


def _response_stream[Data](
    bodies: Generator[bytes, None, None], parse: Callable[[bytes], Data], /
) -> Generator[Data, None, None]:
    # Closing the response stream, or an error in one of its responses, closes the transport's.
    with closing(bodies):
        for body in bodies:
            yield parse(body)


async def _async_response_stream[Data](
    bodies: AsyncGenerator[bytes, None], parse: Callable[[bytes], Data], /
) -> AsyncGenerator[Data, None]:
    async with aclosing(bodies):
        async for body in bodies:
            yield parse(body)


@final
class Client(Generic[_Transport_co]):
    """Run query and mutation requests over *transport*, each call accepting the transport's parameters.

    Several operations of one type run merged, in one call to the transport: a tuple of up to 6 returns a tuple typed position by position, and any other sequence a tuple of their common data type.
    A response with errors raises a :class:`ResponseError`, and a merge an :exc:`ExceptionGroup` of a :class:`ExecutionError` per operation its errors concern, or the unsplit error when its data is null.
    A request from :meth:`~Request.returning_error` gets its :class:`ExecutionError` back in place of its data instead, unless the call raises for another.

    The transport's parameters are read off its signature and checked, so that the library never has to know what they are::

        def transport(body: bytes, /, *, timeout: float | None = None) -> bytes: ...

        client = Client(transport)
        client(ListBooks({"first": 10}), timeout=5.0)

    Code taking a client names its type after the transport's signature, written once as a :class:`typing.Protocol`, which the transport a client is built from is checked against::

        class Transport(Protocol):
            def __call__(self, body: bytes, /, *, timeout: float | None = None) -> bytes: ...

        Client = runtime.Client[Transport]

        def describe(isbn: ISBN, /, *, client: Client) -> str: ...

        describe(isbn, client=Client(transport))

    A plain alias rather than a `type` statement, since only the former can be called to build a client.
    A client is generic over its transport rather than over its parameters, because a :class:`typing.ParamSpec`'s value cannot be spelled with keyword parameters, and PEP 692 only unpacks a concrete :class:`typing.TypedDict`, never a type parameter.
    """

    def __init__(
        self,
        transport: _Transport_co,
        /,
        *,
        injectors: _Injectors | None = None,
    ) -> None:
        self.transport: Final = transport
        self.injectors: Final = injectors

    @overload
    def __call__[**Params, Type: Literal["query", "mutation"], Data](
        self: "Client[Transport[Params]]",
        request: Request[Type, Data],
        /,
        *args: Params.args,
        **kwargs: Params.kwargs,
    ) -> Data: ...
    @overload
    def __call__[**Params, Type: (Literal["query"], Literal["mutation"]), D1, D2](
        self: "Client[Transport[Params]]",
        requests: tuple[Request[Type, D1], Request[Type, D2]],
        /,
        *args: Params.args,
        **kwargs: Params.kwargs,
    ) -> tuple[D1, D2]: ...
    @overload
    def __call__[**Params, Type: (Literal["query"], Literal["mutation"]), D1, D2, D3](
        self: "Client[Transport[Params]]",
        requests: tuple[Request[Type, D1], Request[Type, D2], Request[Type, D3]],
        /,
        *args: Params.args,
        **kwargs: Params.kwargs,
    ) -> tuple[D1, D2, D3]: ...
    @overload
    def __call__[
        **Params,
        Type: (Literal["query"], Literal["mutation"]),
        D1,
        D2,
        D3,
        D4,
    ](
        self: "Client[Transport[Params]]",
        requests: tuple[
            Request[Type, D1], Request[Type, D2], Request[Type, D3], Request[Type, D4]
        ],
        /,
        *args: Params.args,
        **kwargs: Params.kwargs,
    ) -> tuple[D1, D2, D3, D4]: ...
    @overload
    def __call__[
        **Params,
        Type: (Literal["query"], Literal["mutation"]),
        D1,
        D2,
        D3,
        D4,
        D5,
    ](
        self: "Client[Transport[Params]]",
        requests: tuple[
            Request[Type, D1],
            Request[Type, D2],
            Request[Type, D3],
            Request[Type, D4],
            Request[Type, D5],
        ],
        /,
        *args: Params.args,
        **kwargs: Params.kwargs,
    ) -> tuple[D1, D2, D3, D4, D5]: ...
    @overload
    def __call__[
        **Params,
        Type: (Literal["query"], Literal["mutation"]),
        D1,
        D2,
        D3,
        D4,
        D5,
        D6,
    ](
        self: "Client[Transport[Params]]",
        requests: tuple[
            Request[Type, D1],
            Request[Type, D2],
            Request[Type, D3],
            Request[Type, D4],
            Request[Type, D5],
            Request[Type, D6],
        ],
        /,
        *args: Params.args,
        **kwargs: Params.kwargs,
    ) -> tuple[D1, D2, D3, D4, D5, D6]: ...
    @overload
    def __call__[**Params, Type: (Literal["query"], Literal["mutation"]), Data](
        self: "Client[Transport[Params]]",
        requests: Sequence[Request[Type, Data]],
        /,
        *args: Params.args,
        **kwargs: Params.kwargs,
    ) -> tuple[Data, ...]: ...
    def __call__(self, requests: Any, /, *args: Any, **kwargs: Any) -> Any:
        prepared = prepare_requests(requests, injectors=self.injectors)
        return (
            ()
            if prepared is None
            else prepared.parse(self.transport(bytes(prepared), *args, **kwargs))
        )


@final
class AsyncClient(Generic[_AsyncTransport_co]):
    def __init__(
        self,
        transport: _AsyncTransport_co,
        /,
        *,
        injectors: _Injectors | None = None,
    ) -> None:
        self.transport: Final = transport
        self.injectors: Final = injectors

    @overload
    async def __call__[**Params, Type: Literal["query", "mutation"], Data](
        self: "AsyncClient[AsyncTransport[Params]]",
        request: Request[Type, Data],
        /,
        *args: Params.args,
        **kwargs: Params.kwargs,
    ) -> Data: ...
    @overload
    async def __call__[
        **Params,
        Type: (Literal["query"], Literal["mutation"]),
        D1,
        D2,
    ](
        self: "AsyncClient[AsyncTransport[Params]]",
        requests: tuple[Request[Type, D1], Request[Type, D2]],
        /,
        *args: Params.args,
        **kwargs: Params.kwargs,
    ) -> tuple[D1, D2]: ...
    @overload
    async def __call__[
        **Params,
        Type: (Literal["query"], Literal["mutation"]),
        D1,
        D2,
        D3,
    ](
        self: "AsyncClient[AsyncTransport[Params]]",
        requests: tuple[Request[Type, D1], Request[Type, D2], Request[Type, D3]],
        /,
        *args: Params.args,
        **kwargs: Params.kwargs,
    ) -> tuple[D1, D2, D3]: ...
    @overload
    async def __call__[
        **Params,
        Type: (Literal["query"], Literal["mutation"]),
        D1,
        D2,
        D3,
        D4,
    ](
        self: "AsyncClient[AsyncTransport[Params]]",
        requests: tuple[
            Request[Type, D1], Request[Type, D2], Request[Type, D3], Request[Type, D4]
        ],
        /,
        *args: Params.args,
        **kwargs: Params.kwargs,
    ) -> tuple[D1, D2, D3, D4]: ...
    @overload
    async def __call__[
        **Params,
        Type: (Literal["query"], Literal["mutation"]),
        D1,
        D2,
        D3,
        D4,
        D5,
    ](
        self: "AsyncClient[AsyncTransport[Params]]",
        requests: tuple[
            Request[Type, D1],
            Request[Type, D2],
            Request[Type, D3],
            Request[Type, D4],
            Request[Type, D5],
        ],
        /,
        *args: Params.args,
        **kwargs: Params.kwargs,
    ) -> tuple[D1, D2, D3, D4, D5]: ...
    @overload
    async def __call__[
        **Params,
        Type: (Literal["query"], Literal["mutation"]),
        D1,
        D2,
        D3,
        D4,
        D5,
        D6,
    ](
        self: "AsyncClient[AsyncTransport[Params]]",
        requests: tuple[
            Request[Type, D1],
            Request[Type, D2],
            Request[Type, D3],
            Request[Type, D4],
            Request[Type, D5],
            Request[Type, D6],
        ],
        /,
        *args: Params.args,
        **kwargs: Params.kwargs,
    ) -> tuple[D1, D2, D3, D4, D5, D6]: ...
    @overload
    async def __call__[**Params, Type: (Literal["query"], Literal["mutation"]), Data](
        self: "AsyncClient[AsyncTransport[Params]]",
        requests: Sequence[Request[Type, Data]],
        /,
        *args: Params.args,
        **kwargs: Params.kwargs,
    ) -> tuple[Data, ...]: ...
    async def __call__(self, requests: Any, /, *args: Any, **kwargs: Any) -> Any:
        prepared = prepare_requests(requests, injectors=self.injectors)
        return (
            ()
            if prepared is None
            else prepared.parse(await self.transport(bytes(prepared), *args, **kwargs))
        )


@final
class SubscriptionClient(Generic[_SubscriptionTransport_co]):
    """Run subscription requests over *transport*, returning their response stream, which closing unsubscribes.

    A response with errors raises out of the stream.
    """

    def __init__(
        self,
        transport: _SubscriptionTransport_co,
        /,
        *,
        injectors: _Injectors | None = None,
    ) -> None:
        self.transport: Final = transport
        self.injectors: Final = injectors

    def __call__[**Params, Data](
        self: "SubscriptionClient[SubscriptionTransport[Params]]",
        request: Request[Literal["subscription"], Data],
        /,
        *args: Params.args,
        **kwargs: Params.kwargs,
    ) -> Generator[Data, None, None]:
        prepared = prepare(request, injectors=self.injectors)
        return _response_stream(
            self.transport(bytes(prepared), *args, **kwargs), prepared.parse
        )


@final
class AsyncSubscriptionClient(Generic[_AsyncSubscriptionTransport_co]):
    def __init__(
        self,
        transport: _AsyncSubscriptionTransport_co,
        /,
        *,
        injectors: _Injectors | None = None,
    ) -> None:
        self.transport: Final = transport
        self.injectors: Final = injectors

    def __call__[**Params, Data](
        self: "AsyncSubscriptionClient[AsyncSubscriptionTransport[Params]]",
        request: Request[Literal["subscription"], Data],
        /,
        *args: Params.args,
        **kwargs: Params.kwargs,
    ) -> AsyncGenerator[Data, None]:
        prepared = prepare(request, injectors=self.injectors)
        return _async_response_stream(
            self.transport(bytes(prepared), *args, **kwargs), prepared.parse
        )
