# Code generated by graphql-codegen. DO NOT EDIT.

from collections.abc import Callable, Mapping, Sequence
from copy import deepcopy
from typing import Final, Generic, NotRequired, Required, cast, final, override

from ._compat import TypedDict, TypeVar


class Location(TypedDict):
    line: Required[int]
    column: Required[int]


class Error(TypedDict):
    """An error as a server sends it, in the spec's shape, which graphql-core's :class:`~graphql.GraphQLFormattedError` follows too.

    Not graphql-core's :class:`~graphql.GraphQLError`, because four of its eight attributes (:attr:`~graphql.GraphQLError.nodes`, :attr:`~graphql.GraphQLError.source`, :attr:`~graphql.GraphQLError.positions`, and :attr:`~graphql.GraphQLError.original_error`) are server-side execution state a client cannot fill, and importing it would put graphql-core in the runtime for nothing.
    """

    message: Required[str]
    locations: NotRequired[Sequence[Location]]
    path: NotRequired[Sequence[str | int]]
    extensions: NotRequired[object]


class ClientError(Exception):
    """Base of every error a generated client raises.

    A transport's own errors, such as a timeout or an HTTP status, pass through as they are: the client does not know what carries its requests.
    Not :func:`typing.final`: it exists so a caller can catch anything this library raises with one `except`.
    """


class ResponseError(ClientError):
    """The response carried errors, in either of the two shapes the spec gives such a response.

    A response carrying any error raises, so that the data a client returns never holds a `null` standing for an error.
    Not :func:`typing.final`: it exists so a caller can catch both shapes with one `except`.
    """

    def __init__(
        self, errors: Sequence[Error], /, *, extensions: Mapping[str, object] | None
    ) -> None:
        assert errors, "Cannot raise without at least one error."
        self.errors: Final = tuple(errors)
        self.extensions: Final = extensions
        super().__init__("; ".join(error["message"] for error in self.errors))


@final
class RequestError(ResponseError):
    """The response is the spec's request error result: the request failed before execution, so it has no data.

    A syntax error, a validation failure, or an invalid variable value, for instance.
    """


# The type of an execution error's parsed data: the operation's data type when a client returns the error, typed by its request, and a plain mapping when `except` catches it, since that names no operation.
# A legacy `TypeVar`, since a default for a PEP 695 type parameter needs Python 3.13.
_Data_co = TypeVar("_Data_co", covariant=True, default=Mapping[str, object])


@final
class ExecutionError(ResponseError, Generic[_Data_co]):
    """The server raised errors executing the request, but sent the rest of the data.

    A field that raised is `null`, as is its nearest nullable parent if it is non-null.
    """

    data: Final[Mapping[str, object] | None]

    def parse_data(self) -> _Data_co | None:
        """Return the data converted as in a response without errors, in a fresh copy.

        A `@nonNull` field that raised moves its `null` up to its nearest nullable parent, as the server does for a non-null field.
        A custom scalar's codec may raise on a value it cannot decode.
        """
        if self.data is None:
            return None

        data = deepcopy(self.data)

        if self._partial_data_parser is not None:
            try:
                self._partial_data_parser(data)
            except UnexpectedNullError:
                return None

        # Nothing is validated: the data is trusted to match its type, as in a response without errors.
        return cast(_Data_co, data)

    def __init__(
        self,
        errors: Sequence[Error],
        /,
        *,
        data: Mapping[str, object] | None,
        extensions: Mapping[str, object] | None,
        partial_data_parser: Callable[[object], object] | None,
    ) -> None:
        super().__init__(errors, extensions=extensions)
        self.data = data
        self._partial_data_parser: Final = partial_data_parser


@final
class ProtocolError(ClientError):
    """The response was not a GraphQL response.

    Usually an HTML error page from a proxy.
    Without this the caller would get a bare :exc:`json.JSONDecodeError` from somewhere inside the client.
    """


@final
class UnexpectedNullError(ClientError):
    """A field marked `@nonNull` was null.

    The schema declares the field nullable, so only the client can assert otherwise.

    The path names the exact value, list indices included: it is completed on the way up by each enclosing object and list, which costs nothing unless the error is raised.
    """

    def __init__(self, path: list[str | int], /) -> None:
        self.path: Final = path
        super().__init__()

    @override
    def __str__(self) -> str:
        formatted = "".join(
            f"[{segment}]" if isinstance(segment, int) else f".{segment}"
            for segment in self.path
        ).removeprefix(".")
        return f"Expected `{formatted}` to not be null."
