# Code generated by graphql-codegen. DO NOT EDIT.

import typing as _typing

type Genre = _typing.Literal['FICTION', 'NONFICTION', 'POETRY', 'CHILDREN']

type OrderStatus = _typing.Literal['PENDING', 'SHIPPED', 'DELIVERED', 'CANCELED']
