from importlib.metadata import metadata
from typing import Final

METADATA: Final = metadata(__name__.partition(".")[0])
"""This library's metadata, which `pyproject.toml` declares."""

DISTRIBUTION_NAME: Final = METADATA["Name"]
"""This library's name, which only `pyproject.toml` spells."""

# Inspired by https://github.com/github-linguist/linguist/blob/5fbdfcb8133be2bed88bf3ce62b2335f50474525/lib/linguist/generated.rb#L345.
GENERATED_FILE_COMMENT_PREFIX: Final = f"# Code generated by {DISTRIBUTION_NAME}"
